name: rex
favicon: null
layout_spectrum: 0.28034
typography_spectrum: 0.38939
title: Rex
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5780044295825064
  lightness: 0.9729957485105842
  saturation: 0.6429317819420248
  rhythmicContrast: 0.5143175600096583
purpose: []
